version: '3.6'

services:
  db:
    image: mysql
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - "/Users/dimitris/IdeaProjects/rest-api/src/main/resources/mysql/conf.d:/etc/mysql/conf.d"
      - "/Users/dimitris/IdeaProjects/rest-api/src/main/resources/mysql/mysql-data:/var/lib/mysql"
    environment:
      MYSQL_ROOT_PASSWORD: myrootpassword
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
      MYSQL_DATABASE: mydb

  app:
    image: dkarvoyn/rest-api:1.0-SNAPSHOT
    ports:
      - "8080:8080"
